version: '3'
services:

  hiworld1:
    restart: always
    build: ./app
    command: uwsgi --http-socket 0.0.0.0:80 --manage-script-name --mount /web=app:app
    expose:
      - 80

  hiworld2:
    restart: always
    build: ./app
    command: uwsgi --http-socket 0.0.0.0:80 --manage-script-name --mount /web=app:app
    expose:
      - 80

  brokenworld:
    restart: always
    build: ./app
    command: uwsgi --http-socket 0.0.0.0:80 --manage-script-name --mount /web=app:app
    expose:
      - 80
    environment:
      - SLOW_APP=1

  nginx:
    restart: "no"
    build: ./nginx
    links:
      - hiworld1
      - hiworld2
      - brokenworld
    ports:
      - "8080:80"
