version: '3'
services:
  redis:
    image: redis:alpine

  hiworld:
    restart: always
    build: ./app
    command: uwsgi --http-socket 0.0.0.0:80 --manage-script-name --mount /web=app:app
    volumes:
      - ./app:/app
    expose:
      - 80
    links:
      - redis

  brokenworld:
    restart: always
    build: ./app
    command: uwsgi --http-socket 0.0.0.0:80 --manage-script-name --mount /web=app:app
    volumes:
      - ./app:/app
    expose:
      - 80
    links:
      - redis
    environment:
      - SLOW_APP=1

  proxy-custom:
    restart: "no"
    build: ./haproxy
    command: sh -c "/sbin/syslogd -O /proc/1/fd/1 && haproxy -f /usr/local/etc/haproxy/haproxy.cfg -db"
    links:
      - hiworld
      - brokenworld
    ports:
      - "8080:80"
