version: '3'
services:
  redis:
    image: redis:alpine

  hiworld:
    restart: always
    build: ./app
    command: uwsgi --http-socket 0.0.0.0:80 --manage-script-name --mount /web=app:app
    volumes:
      - ./app:/app
    expose:
      - 80
    links:
      - redis

  brokenworld:
    restart: always
    build: ./app
    command: uwsgi --http-socket 0.0.0.0:80 --manage-script-name --mount /web=app:app
    volumes:
      - ./app:/app
    expose:
      - 80
    links:
      - redis
    environment:
      - SLOW_APP=1

  proxy-custom:
    restart: "no"
    build: ./proxy
    links:
      - hiworld
      - brokenworld
    ports:
      - "8080:80"
