version: '3'
services:
  redis:
    image: redis:alpine

  hiworld:
    restart: always
    build: ./app
    command: uwsgi --http-socket 0.0.0.0:80 --manage-script-name --mount /web=app:app
    expose:
      - 80
    links:
      - redis

  brokenworld:
    restart: always
    build: ./app
    command: uwsgi --http-socket 0.0.0.0:80 --manage-script-name --mount /web=app:app
    expose:
      - 80
    links:
      - redis
    environment:
      - SLOW_APP=1

  proxy:
    image: 'dockercloud/haproxy:latest'
    links:
      - hiworld
      - brokenworld
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:80"
    environment:
      - TIMEOUT=connect 5000, client 10000, server 10000
      - HEALTH_CHECK=check inter 1000 rise 2 fall 1
