version: '3'
services:
  web:
    restart: always
    build: .
    command: uwsgi --http-socket localhost:8080 --manage-script-name --mount /web=app:app --plugin python3
    volumes:
      - .:/app
    #expose:
    #  - 80
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
